version: '3.0'
services:
  app:
    container_name: app
    build: app
    depends_on:
      - db
    ports:
      - 8080:80
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'frutimo'
      POSTGRES_USER: 'frutimo'
      POSTGRES_PASSWORD: 'Frut1m0'
    volumes:
      - db:/var/lib/postgresql/data/
volumes:
  db:
