version: '3.0'
services:
  api:
    container_name: api
    build: api
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'frutimo'
      POSTGRES_USER: 'frutimo'
      POSTGRES_PASSWORD: 'Frut1m0'
    volumes:
      - db:/var/lib/postgresql/data/
volumes:
  db:
